### ISSUE TITLE
Awesome idea - can you do ogr2ogr?

### ISSUE THREAD

**Issue by wysisoft** [ddohler/gdal-js#33]
If you can run ogr2ogr in a browser that would be huge.

**Comment by ddohler** [comment]
The short answer is yes, but could I ask a bit more about what uses you have in mind? I've thought about doing this but I do not use `ogr2ogr` heavily in my daily work, so I'm not quite sure how to make it useful for a browser-based application.

**Comment by wysisoft** [comment]
I have a map widget that people use in Power BI, and people are always coming to me and saying "I have KMZ files" or "I have Shapefiles" or "I have csv files" and I don't want to walk them through the command line, and I dont' want to do some server service, I just want to run ogr2ogr for them in the browser. 

https://www.gdal.org/ogr_formats.html

For your testing, i'd see if you can get kml/kmz, shapefile, and csv (WKT) going. I'd be huge for the industry if that was possible.

**Comment by ddohler** [comment]
Thanks for the explanation, that makes sense. I am happy to add this to my to-do list for this project because it sounds clearly useful. Unfortunately, this is a side project for me, and based on my past productivity, it may be months or even more than a year before I can actually get to it. 

However, this functionality should be fairly straightforward to implement using the build setup that's part of this repository already. It'll be necessary to add additional build targets to make `ogr2ogr` instead of `libgdal`: https://github.com/ddohler/gdal-js/blob/develop-js/Makefile#L97 , but that's about it. I don't know how much time you have to spend on this either, but if you are game for giving it a try, I'll be happy to help if you want to put together a PR.

**Comment by pungiish** [comment]
It would be awesome, to run ogr2ogr, I.E. file conversions:  
dxf -> geojson. ogr2ogr command for this is: ogr2ogr -f GeoJSON -s_srs epsg:2154 -t_srs epsg:4326 dest_file.json source_file.dxf

It would really help with the transformation time, uploading large dxf files to a server which transforms them to geojson and then sends them back to the app can take longer than you'd want. I'll try to look it up and help, but not experienced in wasm at all, so it might take long..

**Comment by ddohler** [comment]
Cool, I'm glad to hear you would find this useful as well, @pungiish . As I said previously, I'm happy to provide assistance with creating a PR. I'm also cautiously optimistic that I may have some more time to work on this in the coming months, so this is a timely reminder that this would be a useful feature. I'm currently working on finishing up a 1.0.0 for a gdal-js wrapper library (https://github.com/azavea/loam) but I'll try to put some thought into making ogr2ogr happen after that.

**Comment by ddohler** [comment]
Sorry for the incredibly long delay here, but I've got this nearly finished (thanks to the help from #39 ); I'm planning to have this released within the next few days.
